"""Autogenerate ClickHouse migration operations by diffing models vs the live schema."""

from __future__ import annotations

from dataclasses import dataclass

from alchemiq.clickhouse.ddl import _model_for  # reuse table->model lookup
from alchemiq.clickhouse.model import ch_engine_of
from alchemiq.clickhouse.registry import ch_metadata
from alchemiq.migrations.clickhouse.operations import (
    AddColumn,
    Column,
    CreateTable,
    DropColumn,
    DropTable,
    Operation,
)
from alchemiq.migrations.clickhouse.render import ch_type_string


@dataclass(frozen=True)
class Unsafe:
    """A detected schema change that cannot be applied automatically.

    :ivar kind: category of the unsafe change - one of ``"drop column"``,
        ``"change type"``, ``"change engine"``, or ``"drop table"``.
    :ivar detail: human-readable description including table/column names and old->new values.
    """

    kind: str
    detail: str


def _normalize(t: str) -> str:
    return t.replace(" ", "")


def diff(
    live_tables: set[str],
    live_columns_by_table: dict[str, dict[str, str]],
    live_engines: dict[str, str],
) -> tuple[list[Operation], list[Unsafe]]:
    """Compare registered ClickHouse models against the live schema.

    :param live_tables: table names currently present in the ClickHouse database.
    :param live_columns_by_table: mapping of table name -> column name -> ClickHouse type string.
    :param live_engines: mapping of table name -> engine name (e.g. ``"MergeTree"``).
    :return: a ``(safe, unsafe)`` pair where *safe* is a list of ``Operation``
        objects that can be applied automatically (create table, add column), and
        *unsafe* is a list of ``Unsafe`` descriptors for changes that require
        a hand-written migration (drop column, change type, change engine, drop table).
    """
    safe: list[Operation] = []
    unsafe: list[Unsafe] = []
    model_tables = {t.name: t for t in ch_metadata.sorted_tables}

    for name, table in model_tables.items():
        model_cols = {c.name: ch_type_string(c) for c in table.columns}
        if name not in live_tables:
            cols = [Column(c.name, ch_type_string(c)) for c in table.columns]
            engine = ch_engine_of(_model_for(table)).engine_clause()
            safe.append(CreateTable(name, tuple(cols), engine))
            continue
        live = live_columns_by_table.get(name, {})
        for cname, ctype in model_cols.items():
            if cname not in live:
                safe.append(AddColumn(name, Column(cname, ctype)))
            elif _normalize(live[cname]) != _normalize(ctype):
                unsafe.append(Unsafe("change type", f"{name}.{cname}  {live[cname]} -> {ctype}"))
        for cname in live:
            if cname not in model_cols:
                unsafe.append(Unsafe("drop column", f"{name}.{cname}  (in DB, not in model)"))
        model_engine_name = ch_engine_of(_model_for(table)).engine_clause().split()[2].split("(")[0]
        if live_engines.get(name) and live_engines[name] != model_engine_name:
            unsafe.append(
                Unsafe("change engine", f"{name}  {live_engines[name]} -> {model_engine_name}")
            )

    for name in live_tables:
        if name not in model_tables and not name.startswith("_alchemiq"):
            unsafe.append(Unsafe("drop table", f"{name}  (in DB, not in model)"))
    return safe, unsafe


def inverse(op: Operation) -> Operation:
    """Return the rollback inverse of a safe autogenerated *op*.

    :param op: a safe ``Operation`` produced by ``diff`` (``CreateTable`` or ``AddColumn``).
    :return: the corresponding rollback operation (``DropTable`` or ``DropColumn``).
    :raises ValueError: if *op* has no automatic inverse (e.g. ``DropColumn``).
    """
    if isinstance(op, CreateTable):
        return DropTable(op.name)
    if isinstance(op, AddColumn):
        return DropColumn(op.table, op.column.name)
    raise ValueError(f"no automatic inverse for {type(op).__name__}")
